### ISSUE TITLE
Expired certificates

### ISSUE THREAD

**Issue by michaelkoetter** [Eurex-Clearing-Messaging-Interfaces/Docker-Images#2]
Hi,

first of all thank you for providing these images, they are a great help for local testing and development.
The included certificates for the fixml images expired in May. The only workaround I could find was to change the date of the Docker host - which is less than ideal ;)

Is there a way to create a new set of certificates, or could you provide an updated image?

Thanks in advance
Michael Kötter

**Comment by patbaumgartner** [comment]
Thank you @michaelkoetter for the idea of changing the time in the container. I hope as well that there is soon a fix for the certificates. @scholzj can we expect an update of the certs soon?

Also for us, these images are really valuable and useful during development and testing. Thank you!

**Comment by scholzj** [comment]
Hi Patrick,

I do not work anymore for Eurex and don't have access to these repositories. Please ask @tomas-soltys to fix this.

Jakub

**Comment by tomas-soltys** [comment]
All images (including certificates) were updated.

**Comment by patbaumgartner** [comment]
Thank you very much @tomas-soltys. Your support is very much appreciated. Let's hope travis-ci will run through ;)
